name: "MORPHOS-Azure-Handshake"

on:
  workflow_dispatch:

jobs:
  ping-test:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          # Menggunakan satu rahsia induk JSON
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Sovereign Identity
        run: |
          echo "Handshake Successful. MorphOS Bridge is Online."
          az account show --output table
